-- MySQL Script generated by MySQL Workbench
-- Wed Oct  1 19:40:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- estas tres pueden tirar errores con el server de mysql al igual que las ultimas 3
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `addres` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `rol_id` INT NOT NULL,
  `rol_name` VARCHAR(45) NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UsersDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UsersDetails` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UsersDetails` (
  `user_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `rol_id`),
  INDEX `fk_Users_has_Roles_Roles1_idx` (`rol_id` ASC) VISIBLE,
  INDEX `fk_Users_has_Roles_Users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Roles_Users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Roles_Roles1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `mydb`.`Roles` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enterprise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Enterprise` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Enterprise` (
  `name` VARCHAR(50) NOT NULL,
  `cuit` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cuit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coupons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Coupons` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Coupons` (
  `coupon_id` INT NOT NULL,
  `expiration_date` DATE NOT NULL,
  `price` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `amount` INT NOT NULL,
  `link` VARCHAR(45) NULL,
  `image` BLOB NOT NULL,
  `Enterprise_cuit` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`coupon_id`, `Enterprise_cuit`),
  INDEX `fk_Coupons_Enterprise1_idx` (`Enterprise_cuit` ASC) VISIBLE,
  CONSTRAINT `fk_Coupons_Enterprise1`
    FOREIGN KEY (`Enterprise_cuit`)
    REFERENCES `mydb`.`Enterprise` (`cuit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bottles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bottles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bottles` (
  `bottle_id` INT NOT NULL,
  `plastic_type` VARCHAR(45) NOT NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`bottle_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Scans` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Scans` (
  `user_id` INT NOT NULL,
  `bottle_id` INT NOT NULL,
  `amount` INT NULL,
  `image` BLOB NULL,
  `timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`, `bottle_id`),
  INDEX `fk_Users_has_Bottles_Bottles1_idx` (`bottle_id` ASC) VISIBLE,
  INDEX `fk_Users_has_Bottles_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Bottles_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Bottles_Bottles1`
    FOREIGN KEY (`bottle_id`)
    REFERENCES `mydb`.`Bottles` (`bottle_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RedeemCoupons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RedeemCoupons` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RedeemCoupons` (
  `coupon_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`coupon_id`, `user_id`),
  INDEX `fk_Coupons_has_Users_Users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Coupons_has_Users_Coupons1_idx` (`coupon_id` ASC) VISIBLE,
  CONSTRAINT `fk_Coupons_has_Users_Coupons1`
    FOREIGN KEY (`coupon_id`)
    REFERENCES `mydb`.`Coupons` (`coupon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coupons_has_Users_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

--- este tambien suele explotar en server mysql
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
